hydra:
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
defaults:
  - dataset: fashion_mnist
model:
  name: MobileNet
  initialize: True
training:
  log_file: logs/losses.log
  checkpoint: checkpoints/model.pth
  batch_size: 128
  num_epochs: 100
  n_clusters: 10
  reassign: 1
  use_original_labels: False
  reinitialize: True
  optimizer:
    name: sgd
    lr: 0.05
    momentum: 0.9
    wd: -5
  pca:
    component_size: None
debug_root: debug/
